---
title: "Analysis Multi-Level Models"
output:
  html_document:
    toc: yes
    toc_float: yes
params:
  d_to_model: ""
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading, setting up

```{r, load-packages, message = FALSE}
d_to_model <- params$d_to_model
```

## Descriptives

```{r}
d_to_model %>% 
  select(n_tweets_by_user_in_state,
         voices, 
         national_school_lunch_program_fy_2016_fns_usda_gov,
         pct_students_frpl, 
         state_spending_on_public_elementary_secondary_spending_fy_2016_census_in_thousands,
         state_spending_per_child,
         urban_percentage_of_state_population_in_2015,
         three_year_average_of_state_poverty_rates_2015_2017,
         teacher_salaries_nea_2016,
         c_ideology,
         g_ideology,
         region_by_census,
         enrollment_in_public_ele_sec_education_digest_of_ed_stats_fall_2015_projected,
         staff_teachers,
         coordinators_teachers,
         time_of_account
  ) %>% 
  skimr::skim()
```

## Correlations

```{r}
d_to_model %>% 
  select(n_tweets_by_user_in_state,
         voices, 
         national_school_lunch_program_fy_2016_fns_usda_gov,
         pct_students_frpl, 
         state_spending_on_public_elementary_secondary_spending_fy_2016_census_in_thousands,
         state_spending_per_child,
         urban_percentage_of_state_population_in_2015,
         three_year_average_of_state_poverty_rates_2015_2017,
         teacher_salaries_nea_2016,
         c_ideology,
         g_ideology,
         region_by_census,
         enrollment_in_public_ele_sec_education_digest_of_ed_stats_fall_2015_projected,
         staff_teachers,
         coordinators_teachers,
         time_of_account
  ) %>% 
  corrr::correlate() %>% 
  arrange(desc(n_tweets_by_user_in_state)) %>% 
  corrr::shave() %>% 
  corrr::fashion() %>% 
  knitr::kable()
```

```{r}
d_user_level <- d_to_model %>% 
  distinct(screen_name, .keep_all = TRUE)
```

# Analysis - at the individual level 

```{r, std-vars}
d_user_level$pct_students_frpl_std <- as.vector(scale(d_user_level$pct_students_frpl * 100))
d_user_level$voices_std <- as.vector(scale(d_user_level$voices))

d_user_level$full_time_equivalent_fte_teachers_state_2015_16_std <- as.vector(scale(d_user_level$full_time_equivalent_fte_teachers_state_2015_16))

d_user_level$c_ideology_std <- as.vector(scale(d_user_level$c_ideology))

d_user_level$g_ideology_std <- as.vector(scale(d_user_level$g_ideology))

d_user_level$teacher_student_ratio_std <- as.vector(scale(d_user_level$teacher_student_ratio))

d_user_level$state_spending_per_child_std <- as.vector(scale(d_user_level$state_spending_per_child))

d_user_level$time_of_account_std <- as.vector(scale(d_user_level$time_of_account))
```

```{r, model-null, eval = TRUE}
mnull <- glmer(n_tweets_by_user_in_state ~ 1 + 
                 
                 #scale(time_of_account)+
                 
                 #scale(voices) + 
                 
                 #scale(c_ideology) + 
                 #scale(g_ideology) + 
                 
                 #three_year_average_of_state_poverty_rates_2015_2017 +
                 #fct_students_frpl +
                 
               #state_spending_per_child +
               #total_students_state_2015_16 +
               
               #full_time_equivalent_fte_teachers_state_2015_16 +
               #scale(urban_percentage_of_state_population_in_2015) + 
               
               (1|state), 
               data = d_user_level,
               family = "poisson")

performance::icc(mnull)
sjPlot::tab_model(mnull, show.std = "std")
```

```{r, model-1, eval = TRUE}
m1 <- glmer(n_tweets_by_user_in_state ~ 1 + 
              
                       time_of_account_std +
                       voices_std + 
                       full_time_equivalent_fte_teachers_state_2015_16_std +
                       
                       c_ideology_std + 
                       g_ideology_std + 
                       
                       pct_students_frpl_std + 
                       teacher_student_ratio_std + 
                       state_spending_per_child_std +
              
              (1|state), 
            data = d_user_level,
            family = "poisson")

performance::icc(m1)
sjPlot::tab_model(m1, show.std = "std")
performance::check_model(m1)
margins::margins(m1)
```

Without voices

```{r, model-2, eval = TRUE}
m2 <- glmer(n_tweets_by_user_in_state ~ 1 + 
              
                       time_of_account_std +
                       full_time_equivalent_fte_teachers_state_2015_16_std +
                       
                       c_ideology_std + 
                       g_ideology_std + 
                       
                       pct_students_frpl_std + 
                       teacher_student_ratio_std + 
                       state_spending_per_child_std +
              
              (1|state), 
            data = d_user_level,
            family = "poisson")

performance::icc(m2)
sjPlot::tab_model(m2, show.std = "std")
performance::check_model(m2)
margins::margins(m2)
```