---
title: "Analysis Linear Models"
output:
  html_document:
    toc: yes
    toc_float: yes
params:
  d_to_model: ""
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading, setting up

```{r, load-packages, message = FALSE}
d_to_model <- params$d_to_model
```

# State-level descriptives

```{r}
distinct_states <- d_to_model %>% 
  distinct(state, .keep_all = TRUE) %>% 
  select(-user_id, -screen_name, -created_at)
```

## Descriptives

```{r}
distinct_states %>% 
  select(n_tweets_at_state_level,
         n_tweets_by_user_in_state,
         voices, 
         full_time_equivalent_fte_teachers_state_2015_16,
         c_ideology,
         g_ideology,
         pct_students_frpl,
         teacher_student_ratio,
         state_spending_per_child,
         time_of_account
  ) %>% 
  skimr::skim()
```

## Correlations

```{r}
distinct_states %>% 
  select(n_tweets_at_state_level,
         n_tweets_by_user_in_state,
         voices, 
         full_time_equivalent_fte_teachers_state_2015_16,
         c_ideology,
         g_ideology,
         pct_students_frpl,
         teacher_student_ratio,
         state_spending_per_child,
         time_of_account
  ) %>% 
  corrr::correlate() %>% 
  arrange(desc(n_tweets_at_state_level)) %>% 
  corrr::shave() %>% 
  corrr::fashion() %>% 
  knitr::kable()
```

## Analysis - n tweets at state level

## Some linear models

```{r, state-level-models}
m_state_level <- glm(n_tweets_at_state_level ~ 1 + 
                       
                       scale(voices) + 
                       scale(full_time_equivalent_fte_teachers_state_2015_16) +
                       
                       scale(c_ideology) + 
                       scale(g_ideology) + 
                       
                       scale(pct_students_frpl) +
                       scale(teacher_student_ratio) + 
                       scale(state_spending_per_child),
                     data = distinct_states, 
                     family = "poisson")

sjPlot::tab_model(m_state_level, show.std = "std")
performance::check_model(m_state_level)
margins::margins(m_state_level)
```

### Without voices - use this one

```{r, state-level-models-no-voices}
m_state_level_no_voices <- glm(n_tweets_at_state_level ~ 1 + 
                       
                       #scale(voices) + 
                       scale(full_time_equivalent_fte_teachers_state_2015_16) +
                       
                       scale(c_ideology) + 
                       scale(g_ideology) + 
                       
                       scale(pct_students_frpl) +
                       scale(teacher_student_ratio) + 
                       scale(state_spending_per_child),
                     data = distinct_states, 
                     family = "poisson")

sjPlot::tab_model(m_state_level_no_voices, show.std = "std")
performance::check_model(m_state_level_no_voices)
margins::margins(m_state_level_no_voices)
```


## Analysis - users at state level

## Some linear models

```{r, state-level-models-users}
m_state_level_users <- glm(voices ~ 1 + 
                       
                       scale(full_time_equivalent_fte_teachers_state_2015_16) +
                       
                       scale(c_ideology) + 
                       scale(g_ideology) + 
                       
                       scale(pct_students_frpl) +
                       scale(teacher_student_ratio) + 
                       scale(state_spending_per_child),
                     data = distinct_states, 
                     family = "poisson")

sjPlot::tab_model(m_state_level_users, show.std = "std")
performance::check_model(m_state_level_users)
margins::margins(m_state_level_users)
```